// DATA SOURCES
export enum DATABASE_SOURCES {
  DATA_SOURCE = 'DATA_SOURCE', // MASTER DATA SOURCE
}
// REPOSITORY PROVIDERS
export enum DB_CONST_REPOSITORY {
  USER = 'USER_REPOSITORY',
  USER_HISTORY = 'USER_HISTORY_REPOSITORY',
}
