export enum RESPONSE_STATUS {
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
  NO_ACCESS_TOKEN = 'NO_ACCESS_TOKEN',
  ACCESS_TOKEN_EXP = 'ACCESS_TOKEN_EXP',
  NO_REFRESH_TOKEN = 'NO_REFRESH_TOKEN',
  REFRESH_TOKEN_EXP = 'REFRESH_TOKEN_EXP',
}
